# -*- coding: utf-8 -*-
"""NTU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-g5RCZfEbqB3E2DW3nddrApsuBH1YzpN
"""

# Base class representing a human
class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name}, Age: {self.age}"

# Student class extending Human
class Student(Human):
    def __init__(self, name, age, roll_number):
        super().__init__(name, age)
        self.roll_number = roll_number

    def __str__(self):
        return f"Student: {self.name}, Roll No: {self.roll_number}, Age: {self.age}"

# Teacher class extending Human
class Teacher(Human):
    def __init__(self, name, age, subject):
        super().__init__(name, age)
        self.subject = subject

    def __str__(self):
        return f"Teacher: {self.name}, Subject: {self.subject}"

# Section class containing section properties
class Section:
    def __init__(self, name, timing, teacher, students):
        self.name = name
        self.timing = timing
        self.teacher = teacher
        self.students = students

    def __str__(self):
        students_list = "\n".join([str(student) for student in self.students])
        return (f"Section: {self.name}\n"
                f"Timing: {self.timing}\n"
                f"Teacher: {self.teacher}\n"
                f"Students:\n{students_list}")

# University class containing student and teacher arrays
class University:
    def __init__(self, name):
        self.name = name
        self.students = []
        self.teachers = []

    def add_student(self, student):
        self.students.append(student)

    def add_teacher(self, teacher):
        self.teachers.append(teacher)

    def __str__(self):
        students_list = "\n".join([str(student) for student in self.students])
        teachers_list = "\n".join([str(teacher) for teacher in self.teachers])
        return (f"University: {self.name}\n\n"
                f"Teachers:\n{teachers_list}\n\n"
                f"Students:\n{students_list}")

# Create University, Teachers, Students, and Sections
ntu = University("National Textile University")

# Teachers
teacher1 = Teacher("Naveed Sarwar", 40, "AI")
teacher2 = Teacher("Abu Hurairah", 35, "Data Science")
ntu.add_teacher(teacher1)
ntu.add_teacher(teacher2)

# Students (Ages updated to 16)
student1 = Student("Abeerah", 16, "AI-01")
student2 = Student("Saira", 16, "AI-02")
ntu.add_student(student1)
ntu.add_student(student2)

# Section
section = Section("Quarter 1", "2:00 AM - 6:00 AM", teacher1, [student1, student2])

# Display Results
print(ntu)
print("\nSection Details:\n", section)